### ISSUE TITLE
Allow apply rules by formatting the recipe

### ISSUE THREAD

**Issue by jetm** [priv-kweihmann/oelint-adv#19]
There are rules like `oelint.spaces.lineend` or `oelint.tabs.notabs` could be triggered and automatically fix the error or warn found.

**Comment by priv-kweihmann** [comment]
@jetm thanks for that suggestion - I'll see what I can do.
From my point of view this could also be extended to much more rules...

**Comment by priv-kweihmann** [comment]
@jetm I just pushed a quick implementation to branch 'autofix'. Could you please have a look at it and tell me if that fits your needs! Thanks
