### ISSUE TITLE
SRC_URI mandotory in recipes-image?

### ISSUE THREAD

**Issue by vermaete** [priv-kweihmann/oelint-adv#199]
The linter is returning a SRC_URI is mandatory on an image recipe in recipes-images.
Could it be this is a false positive?
At least I don't see the real need to have a SRC_URI in an image recipe.

Br,

**Comment by priv-kweihmann** [comment]
ofc it isn't - same applies to packagegroup recipes - I take this as an improvement.
Currently some rules should be deactivated (like done here https://github.com/priv-kweihmann/meta-sca/blob/2d93d1770e32b592750da917ee3451a8b953d9b6/classes/sca-oelint-core.bbclass#L108) on image recipes.

The hard part is to determine is if a recipe inherits the image.bbclass, as this can be hidden under various layers of inherits.
I'm open to idea how to do that
