### ISSUE TITLE
How to mute check for single suggested variable?

### ISSUE THREAD

**Issue by skycaptain** [priv-kweihmann/oelint-adv#220]
I find the `oelint.var.suggestedvar` really helpful, as it keeps code quality high and "forces" developers to add proper metadata. While IMHO all suggested variables make sense, I would argue that `CVE_PRODUCT` is often not applicable to recipes of non-public software, i.e. enterprise embedded software. While I would still use the check for all other variables it would be great to be able to mute the check for a single variable. I tried to use `--suppress oelint.var.suggestedvar.CVE_PRODUCT`, however this muted all suggestions, not only `CVE_PRODUCT`.

**Comment by skycaptain** [comment]
I guess this could be done by creating a rule class for each suggested var, possibly also dynamically. Shall I open a PR?

**Comment by priv-kweihmann** [comment]
yes, that could be done, but this here sounds more like a bug to me - I will check on that later

**Comment by priv-kweihmann** [comment]
Yes it's a bug :-(

**Comment by skycaptain** [comment]
Once again thank you @priv-kweihmann, I really appreciate your work and engagement. I've tested 2.5.1; works like a charm!

**Comment by skycaptain** [comment]
I'm now also able to disable certain other "subrules" and streamline everything.

Unfortunately, your recent change only seems to work with `--suppress` from the CLI but not with rulefiles. I'm also not able to just set `"oelint.var.suggestedvar.CVE_PRODUCT": "info"` inside the rulefile and use `--noinfo` with the CLI; oelint.var.suggestedvar.CVE_PRODUCT infos are still reported.

**Comment by priv-kweihmann** [comment]
@skycaptain yep, haven't looked at that, but it's likely to be like you reported. Could you please open another ticket and I will address that in a Bugfix release - thx
