### ISSUE TITLE
Broken output format with default severity in rules 

### ISSUE THREAD

**Issue by offa** [priv-kweihmann/oelint-adv#241]
The output format contains a `::` instead of the actual severity when a rulefile with default severities is used.

```
[...]/example.bb:34::oelint.newline.eof:File shall end on a newline
                   ^^ 
```

The issue appears with `""` severities in the rulefile only. Not using a rulefile or setting explicit severities works fine.

3.0.x versions aren't affected.

### Reproduction

1. Install oelint-adv v3.1.0
2. Create a rulefile containing default severities (= `""`)
3. Lint a file
4. Verify `::` is printed instead of the severity

### Workaround

- _(a)_ Set explicit severities instead of using the default
- _(b)_ Downgrade to 3.0.x

**Comment by Rahix** [comment]
Okay, looks like I'm to blame for that...  The issue is in the new `GetSeverity()` function:

https://github.com/priv-kweihmann/oelint-adv/blob/b9dc381b181a8bdc7300bb5070f80bf90950efbd/oelint_adv/cls_rule.py#L107-L126

I'll try to send a PR today!
