### ISSUE TITLE
Output is not sorted by file

### ISSUE THREAD

**Issue by alub** [priv-kweihmann/oelint-adv#420]
Hello,

I’m running `oelint-adv==3.22.4` and I would have expected the output to be sorted by file and line for easier review, and that is not the case: I see some files intertwined in the output. Surprisingly, that doesn’t seem to depend on the number of jobs, I even see that with 1 job.

**Comment by priv-kweihmann** [comment]
Indeed it's sorted by line - file so far never has been taken into consideration - but I can try to fix that - seems to be a good to have improvement
