### ISSUE TITLE
rulefile: rule groups can only be enabled/disabled as a whole

### ISSUE THREAD

**Issue by jankraing** [priv-kweihmann/oelint-adv#436]
Including the following section in the rulefile.json

```
  "oelint.var.mandatoryvar": "error",
  "oelint.var.mandatoryvar.DESCRIPTION": "error",
  "oelint.var.mandatoryvar.LICENSE": "error",
  "oelint.var.mandatoryvar.SRC_URI": "error",
```

enables all mandatoryvar subrules, including SUMMARY and HOMEPAGE.

Leaving out ` "oelint.var.mandatoryvar": "error",` results in no errors even for DESCRIPTION, LICENSE and SRC_URI.

**Comment by jankraing** [comment]
After looking into it, I'm really not sure how to solve this or if you even want to change this behavior.
Maybe a "none" severity level could be added to ignore/exclude (sub-)rules like so:

```
 if _severity == 'none':
            return []
```

For now I will change severity in the rulefile to "none" and ignore issues with "none" severity further down in the pipeline.

**Comment by priv-kweihmann** [comment]
Yup, I was thinking about how to solve this as well for quite some time now - your proposal with 'none'/'null' sounds like a way to make it work - will look into it, if work allows that this week
