### ISSUE TITLE
Release option in config file

### ISSUE THREAD

**Issue by offa** [priv-kweihmann/oelint-adv#489]
The `--release` option is a nice feature :+1:, but as far as I have tested it's not configurable though `.oelint.cfg` yet.

It would be great to enable it in the .cfg file so different tools can use same options.

**Comment by priv-kweihmann** [comment]
Damn, you're right - will fix that in the next couple of days

**Comment by priv-kweihmann** [comment]
it actually works right out of the box e.g.

```ini
[oelint]
release=kirkstone
```

works for me

**Comment by priv-kweihmann** [comment]
Works for me

```ini
[oelint]
release=dunfell
```

does configure dunfell release.
Added an example to the README - feel free to close it if you think that is enough

**Comment by offa** [comment]
Thanks for verification, I'll check this again.

**Comment by offa** [comment]
Issue on my end, sorry.
