### ISSUE TITLE
bbclass filename caveats 

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/oelint-adv#493]
https://bugzilla.yoctoproject.org/show_bug.cgi?id=14235 shows interesting things to check for

**Comment by offa** [comment]
I'm not sure whether the `-`-instead-of-`_` is a good suggestion. It has issues on it's own and as the linked discussion shows, it's difficult to say what's correct one.

**Comment by priv-kweihmann** [comment]
I see - will promote _ then instead of dash.
Hopefully upstream will finally decide on a common pattern
