### ISSUE TITLE
[feature] Shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [priv-kweihmann/oelint-adv#523]
Can it provide completions for common shells? I guess <https://docs.iterative.ai/shtab/> can be helpful. TIA!

**Comment by priv-kweihmann** [comment]
I'm more of a fan of https://pypi.org/project/argcomplete/ - but yes that could be a lovely feature to have

**Comment by Freed-Wu** [comment]
Oh,  shtab said it is faster than argcomplete <https://docs.iterative.ai/shtab/#alternatives>

However, use what depends on you :smile:
