### ISSUE TITLE
[feature] Python port

### ISSUE THREAD

**Issue by Freed-Wu** [priv-kweihmann/oelint-adv#524]
Can it provide a python port? Such as:

`test.py`:

```python
#!/usr/bin/env python
from oelint_adv import check, format_result
with open("XXX.bb") as f:
    text = f.read()
result = check(text)
print(format_result(result))
```

```sh
$ ./test.py
/disk/meta-some/cppcheck-native/cppcheck.inc:26:error:oelint.task.nomkdir:'mkdir' shall not be used in do_install. Use 'install'
```

**Comment by priv-kweihmann** [comment]
Did I get that right, you want to use oelint-adv as part of a library?
If so, yes that could be done

**Comment by Freed-Wu** [comment]
Yes, I want :smile:

**Comment by Freed-Wu** [comment]
Current python port is:

```python
for issue in run(create_lib_arguments([path])):
```

Can we have an optional document content?

When we

```python
for issue in run(create_lib_arguments([path], [content])):
```

It will ignore the file content of `path`, and use `content` to replace?

It can be helpful for the file content of path is modified, however, the
modification only exist in buffer of editor, have not be written to hard disk.

**Comment by priv-kweihmann** [comment]
Sure, I take that into the backlog
