### ISSUE TITLE
[feature] Wiki/website with description for messages

### ISSUE THREAD

**Issue by jo-so** [priv-kweihmann/oelint-adv#530]
Similar to Rust's clippy a website describing the background and possibly the fixing of the lint messages. A random example: [Clippy Lints *manual\_range_contains*](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_range_contains)

**Comment by priv-kweihmann** [comment]
Nice idea, patches welcome

**Comment by jo-so** [comment]
Amazing. It's really impressing what you've achieved.
