### ISSUE TITLE
[feature] Give link to wiki pages in output

### ISSUE THREAD

**Issue by jo-so** [priv-kweihmann/oelint-adv#535]
Following up on #530 I would like to ask if it's possible to enhance the output of oelint-adv to print a weblink to the wiki page (maybe with an option `--show-wiki-link`).

And would it be possible to get an enhanced message format (e.g. `--urls-in-message`) to get links to the wiki and the path? Maybe add new placeholder `path-link` and `id-link` they emit the required escape sequences ([Hyperlinks in Terminal Emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda), [Alhadis/OSC8-Adoption: List of terminal emulators that support hyperlinks (OSC 8 escape sequences).](https://github.com/Alhadis/OSC8-Adoption)). While this could always be done, it would be more handy to have options to emit all these sequences.

```
oelint-adv --quiet --relpaths --color --messageformat $'\033]8;;file://$PWD/{path}\033\\{path}\033]8;;\033\\:{line}:{severity}:\033]8;;https://github.com/priv-kweihmann/oelint-adv/blob/master/docs/wiki/{id}.md\033\\{id}\033]8;;\033\\:{msg}'
```

**Comment by priv-kweihmann** [comment]
I guess that wouldn't be that complicated if a new ``messageformat`` placeholder "wikiurl" would be added.
By default it would be off, but could be added in the way your described above - will take that later that week (if time allows)
