### ISSUE TITLE
Ignore lint on file

### ISSUE THREAD

**Issue by corco** [priv-kweihmann/oelint-adv#596]
I couldn't find a way to entirely ignore a file for linting.

In our use-case, we have a rust application recipe (`app_1.0.bb`) that `require app_crates.inc` which is auto-generated.

The linter triggers on `app_crates.inc` because of spacing. We would rather not modify that file since it is auto-generated, is there a way to suppress lint only for that file without modifying it? Either entirely for by-lint?

**Comment by priv-kweihmann** [comment]
No there is nothing of that kind yet - I remember that question coming up recently...
My personal take is, fix the generator to produce valid, lint free bitbake recipe code.

I'm concerned that if the linter would have such an option, people will start to cramp up everything into these suppressed files,
which is entirely is against the purpose of a linter.

Ofc for very special cases the linter can be run in lib-mode, so a calling script could filter out whatever is needed.

**Comment by priv-kweihmann** [comment]
See https://github.com/priv-kweihmann/oelint-adv/discussions/598
