### ISSUE TITLE
False positive with inline functions

### ISSUE THREAD

**Issue by UVV-gh** [priv-kweihmann/oelint-adv#597]
Seems like this case:
`SRC_URI:append = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'my-feature', '', ' file://0001-my-patch.patch', d)}"`
is reported as an `append` without space. Any ideas how to fix it properly?

**Comment by priv-kweihmann** [comment]
The inline functions are evaluated always by their true branch statement - if you would negated the condition and switch true and false branch statement it should be fine.
It admit it's a limitation of the parser used

**Comment by priv-kweihmann** [comment]
The other option is ofc to inject a pseudo space into the true branch statement

**Comment by UVV-gh** [comment]
Any way to disable a warning/error when inline function is used?

**Comment by priv-kweihmann** [comment]
Inline suppression should work (https://github.com/priv-kweihmann/oelint-adv#inline-suppression).

**Comment by priv-kweihmann** [comment]
Support for negative branch check was added with #611 and released with version 6.0.0
