### ISSUE TITLE
Check for `Upstream-Status` value

### ISSUE THREAD

**Issue by tym2k1** [priv-kweihmann/oelint-adv#610]
It would be beneficial to implement a rule that triggers a warning or error message if the `Upstream-Status` variable in a patch is set to specific values, such as `Pending`. The `Pending` value is often used during development to suppress errors when the Upstream-Status is not set, but it is not suitable for production environments. This rule would help prevent patches with inappropriate `Upstream-Status` values from being merged into production, reducing the maintainance burden in in the long run.

[Upstream-Status documentation](https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status)

**Comment by priv-kweihmann** [comment]
One idea would be to allow an appendix to the rule ID in the implementation of https://github.com/priv-kweihmann/oelint-adv/blob/master/oelint_adv/rule_base/rule_file_patch_upstreamstatus.py.
Like this you could error out (with a custom rulefile - https://github.com/priv-kweihmann/oelint-adv/tree/master?tab=readme-ov-file#defining-a-ruleset).
I will try to come up with an implementation in the next couple of weeks
