### ISSUE TITLE
oelint.vars.multilineident matches not fully Yocto style guide

### ISSUE THREAD

**Issue by jo-so** [priv-kweihmann/oelint-adv#613]
While https://github.com/priv-kweihmann/oelint-adv/blob/6.0.0/docs/wiki/oelint.vars.multilineident.md says:

```
A = "\
    a \
    b \
"
```

https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#variable-formatting says

```
FOO = "this line is \
       long \
       "
```

The first aligns at `"` and the second at the character after `"`. Which one is right?

**Comment by priv-kweihmann** [comment]
https://www.openembedded.org/index.php?title=Styleguide&oldid=10281 mentions even more 😁.

I personally like the linter variant much more in terms of readability, but the checks do work on both afaik (and it was in line with the style guide at that time)

I am not sure why that was changed in the current style guide (there is sadly not much  transparency and reasoning available).
