### ISSUE TITLE
Inline suppression of oelint.var.mandatoryvar

### ISSUE THREAD

**Issue by pasweistorz** [priv-kweihmann/oelint-adv#654]
Hi,

we're writing a custom Linux kernel recipe in a custom layer and in order to avoid code duplication we're reusing the file `linux-yocto.inc` from poky. Some variables like `SUMMARY` and `LICENSE` are already defined there., so there's no need for us to define them again in our recipe We're using `oelint-adv` via the `meta-sca` layer. Because `oelint-adv` doesn't support requiring files across layers (#626) we want to suppress the `oelint.var.mandatoryvar.SUMMARY` and `oelint.var.mandatoryvar.LICENSE` errors found by the linter.

An inline suppression of those errors is possible, but only if we add the `# nooelint` entry into the first line of the recipe. I think the reason for this is, that such a finding is issued with a line number of `0` and when looking for an inline suppression of such a finding the maximum of `1` and `_suppression_offset - 1` is checked (which is `max(1, -1) = 1` here), see https://github.com/priv-kweihmann/oelint-adv/blob/master/oelint_adv/cls_rule.py#L151.

Is this intended behaviour? Shouldt the location of the inline suppression not be irrelevant in this case?

Another side effect of adding an inline suppression for `oelint.var.mandatoryvar.SUMMARY` is that we get another new linter info `info:oelint.file.inlinesuppress_na:Inline suppression for 'oelint.var.mandatoryvar.SUMMARY' is not needed`. The reason for this might be that `_suppression_offset - 1` is passed to `set_inline_suppression_seen` instead of `max(1, _suppression_offset - 1)`, see https://github.com/priv-kweihmann/oelint-adv/blob/master/oelint_adv/cls_rule.py#L152.

Thanks for investigating.

**Comment by priv-kweihmann** [comment]
Easiest solution is to add SUMMARY and LICENSE as a weak define `?=`  to the recipe before the include.

BTW including linux-yocto.inc into a custom kernel is a bad idea in itself.
Custom kernel should depend on kernel (and potentially kernel-yocto) bbclasses only.
That makes also all the stuff go away in an instant.

The only thing I tend to fix `oelint.file.inlinesuppress_na` issue - but it has rather low priority for me
