### ISSUE TITLE
Underscore in filename error triggered because of dash in the version

### ISSUE THREAD

**Issue by albard00** [priv-kweihmann/oelint-adv#668]
Hi,

I am wondering why this code is checking also on dashes and not only underscores.

https://github.com/priv-kweihmann/oelint-adv/blob/0cd2183810cd1ab829006f9483bfe0e400d8ace8/oelint_adv/rule_base/rule_file_underscores.py#L22

I am often using a dash in the version number to highlight a customization of an upstream version.
For example:
linux-yocto_6.6-custom.bb

And this triggers this rule for no good reason in my opinion.

Thanks for your answer.

**Comment by priv-kweihmann** [comment]
Not sure where the ` -`  in the first list originates from (seems to be the beginning of time) - but I believe this can go.
Patches welcome
